;;; file 08

(boolean? #t)
(boolean? #f)
(boolean? 1234)
(boolean? 'a)
(symbol? 'b)
(procedure? procedure?)
(eq? (car '(a b c)) 'a)
(= (car (cons 1 2)) 1)
(integer? 1234)
(char? #\a)
(null? '())
(string? "abc")
(symbol? 'lambda)
(vector? '#(1 2 3))
(vector? 1234)
(string? '#(a b c))
(string? 1234)
(= 3 (vector-length '#(a #t ())))
(pair? '(a . b))
(pair? '())
(zero? 0)
(zero? 234)
(+ 2 2/3)
(* 1/3 3/5 5/7)
(+ 1/2 1/3)
